# Generated by Django 5.2.14 on 2026-05-23 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('name', models.CharField(help_text='Purpose label, e.g. Hall Renovation, AC Purpose.', max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive purposes are hidden from new donations.')),
            ],
            options={
                'verbose_name': 'donation purpose',
                'verbose_name_plural': 'donation purposes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('name', models.CharField(help_text='Membership tier label, e.g. Silver, Golden, Diamond.', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tiers are hidden from new registrations.')),
            ],
            options={
                'verbose_name': 'membership tier',
                'verbose_name_plural': 'membership tiers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. True = logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the row was soft-deleted.', null=True)),
                ('donor_id', models.CharField(db_index=True, help_text='Unique donor identifier, e.g. DH-2024-8842.', max_length=30, unique=True)),
                ('district_code', models.CharField(blank=True, help_text='Normalized district code, e.g. V101A, V203A.', max_length=20)),
                ('club_name', models.CharField(blank=True, help_text='Club name, e.g. KCGF Warangal.', max_length=200)),
                ('for_place', models.ForeignKey(blank=True, help_text='Branch where the donor sent their donation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donors_for_place', to='branches.branch')),
                ('user', models.OneToOneField(help_text='The user account linked to this donor profile.', limit_choices_to={'role': 'donor'}, on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
                ('membership_tier', models.ForeignKey(help_text="Donor's current membership tier.", on_delete=django.db.models.deletion.PROTECT, related_name='donors', to='donors.membershiptier')),
            ],
            options={
                'verbose_name': 'donor profile',
                'verbose_name_plural': 'donor profiles',
                'ordering': ['donor_id'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('amount', models.BigIntegerField(help_text='Amount in paise (₹1 = 100 paise).')),
                ('dispatch_date', models.DateField(blank=True, help_text='Date when coupons were physically dispatched.', null=True)),
                ('dispatch_method', models.CharField(blank=True, choices=[('courier', 'Courier'), ('by_hand', 'By Hand'), ('other', 'Other')], help_text='How coupons were dispatched.', max_length=20)),
                ('dispatch_notes', models.TextField(blank=True, help_text='Free-text dispatch notes.')),
                ('created_by', models.ForeignKey(help_text='Must be a super_admin.', limit_choices_to={'role': 'super_admin'}, on_delete=django.db.models.deletion.PROTECT, related_name='donations_created', to=settings.AUTH_USER_MODEL)),
                ('purpose', models.ForeignKey(help_text='What the donation is earmarked for.', on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donors.donationpurpose')),
                ('donor', models.ForeignKey(help_text='The donor who made this contribution.', on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donors.donorprofile')),
            ],
            options={
                'verbose_name': 'donation',
                'verbose_name_plural': 'donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('receipt_number', models.CharField(help_text='Individual receipt number, e.g. 6804/2020.', max_length=50)),
                ('donation', models.ForeignKey(help_text='The donation this receipt belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='receipt_numbers', to='donors.donation')),
            ],
            options={
                'verbose_name': 'receipt number',
                'verbose_name_plural': 'receipt numbers',
                'ordering': ['receipt_number'],
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor'], name='idx_donation_donor'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='donation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receiptnumber',
            constraint=models.UniqueConstraint(fields=('donation', 'receipt_number'), name='uq_donation_receipt'),
        ),
    ]
