# Generated by Django 5.2.14 on 2026-05-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('scope', models.CharField(db_index=True, max_length=64)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('request_body_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('response_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('user_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'idempotency record',
                'verbose_name_plural': 'idempotency records',
                'indexes': [models.Index(fields=['scope', 'status'], name='idx_idem_scope_status')],
            },
        ),
    ]
