# Generated by Django 5.2.14 on 2026-05-23 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('branches', '0001_initial'),
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('coupon_type', models.CharField(choices=[('concession', 'Concession'), ('free', 'Free')], max_length=20)),
                ('serial_start', models.PositiveIntegerField()),
                ('serial_end', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField(help_text='Number of coupons in this batch. Must equal serial_end - serial_start + 1.')),
                ('extra_benefit', models.TextField(blank=True, help_text='e.g. 50% Concession in Hall Booking for 1 Day.')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_batches', to='donors.donation')),
            ],
            options={
                'verbose_name': 'coupon batch',
                'verbose_name_plural': 'coupon batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. True = logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the row was soft-deleted.', null=True)),
                ('serial_number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('coupon_type', models.CharField(choices=[('concession', 'Concession'), ('free', 'Free')], max_length=20)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('dispatched', 'Dispatched'), ('redeemed', 'Redeemed')], db_index=True, default='issued', max_length=20)),
                ('redeemed_on', models.DateTimeField(blank=True, null=True)),
                ('assigned_donors', models.ManyToManyField(blank=True, help_text='If empty, coupon is available to all donors. If populated, only listed donors may use it.', related_name='assigned_coupons', to=settings.AUTH_USER_MODEL)),
                ('redeemed_at_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_coupons', to='bookings.booking')),
                ('redeemed_at_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_coupons', to='branches.branch')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_coupons', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='coupons.couponbatch')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'ordering': ['serial_number'],
            },
        ),
        migrations.AddIndex(
            model_name='couponbatch',
            index=models.Index(fields=['donation'], name='idx_couponbatch_donation'),
        ),
        migrations.AddConstraint(
            model_name='couponbatch',
            constraint=models.CheckConstraint(condition=models.Q(('serial_end__gte', models.F('serial_start'))), name='batch_serial_end_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='couponbatch',
            constraint=models.CheckConstraint(condition=models.Q(('count__gt', 0)), name='batch_count_positive'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status'], name='idx_coupon_status'),
        ),
    ]
