# Generated by Django 5.2.15 on 2026-06-14 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_add_composite_indexes'),
        ('branches', '0002_convert_to_uuid_pk'),
        ('coupons', '0002_convert_to_uuid_pk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['batch', 'status'], name='idx_coupon_batch_status'),
        ),
    ]
