# Generated by Django 5.2.14 on 2026-05-23 12:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. True = logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the row was soft-deleted.', null=True)),
                ('phone', models.CharField(db_index=True, help_text="Primary identifier; 10–15 digits, optional leading '+'.", max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number (10–15 digits, optional leading '+').", regex='^\\+?\\d{10,15}$')])),
                ('name', models.CharField(blank=True, help_text='Full display name of the user.', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Optional email address (not used for authentication).', max_length=254, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('donor', 'Donor'), ('admin', 'Branch Admin'), ('super_admin', 'Super Admin')], default='user', help_text='Determines UI capabilities and API permissions.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.')),
                ('is_first_login', models.BooleanField(default=True, help_text='True until the user confirms their profile after first OTP login.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of account creation.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='AdminBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the assignment was created.')),
                ('assigned_by', models.ForeignKey(help_text='The super-admin who made this assignment.', limit_choices_to={'role': 'super_admin'}, on_delete=django.db.models.deletion.PROTECT, related_name='admin_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(help_text='The branch this admin is responsible for.', on_delete=django.db.models.deletion.CASCADE, related_name='branch_admins', to='branches.branch')),
                ('user', models.OneToOneField(help_text='The branch-admin user being assigned.', limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_branch', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin branch assignment',
                'verbose_name_plural': 'admin branch assignments',
            },
        ),
        migrations.CreateModel(
            name='OTPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('phone', models.CharField(db_index=True, help_text='Phone number the OTP was sent to.', max_length=15)),
                ('hashed_otp', models.CharField(help_text='Argon2/PBKDF2 hashed OTP via make_password.', max_length=128)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('registration', 'Registration')], default='login', help_text='Reason the OTP was issued.', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Set to True once the OTP is successfully verified.')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of consecutive failed verification attempts.')),
                ('locked_until', models.DateTimeField(blank=True, help_text='If set, the OTP cannot be verified until this time.', null=True)),
                ('expires_at', models.DateTimeField(help_text='Auto-set to created_at + 60 seconds on save.')),
            ],
            options={
                'verbose_name': 'OTP log',
                'verbose_name_plural': 'OTP logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'created_at'], name='idx_otp_phone_created')],
            },
        ),
        migrations.CreateModel(
            name='ProfileConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('is_confirmed', models.BooleanField(default=False, help_text='True once the user has confirmed their profile.')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Timestamp of when the profile was confirmed.', null=True)),
                ('user', models.OneToOneField(help_text='The user whose profile confirmation this tracks.', on_delete=django.db.models.deletion.CASCADE, related_name='profile_confirmation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile confirmation',
                'verbose_name_plural': 'profile confirmations',
            },
        ),
    ]
