# Generated by Django 5.2.15 on 2026-06-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_convert_to_uuid_pk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adminbranch',
            unique_together={('user',)},
        ),
        migrations.AddIndex(
            model_name='otplog',
            index=models.Index(fields=['phone', 'is_verified', 'created_at'], name='idx_otp_phone_verified_created'),
        ),
    ]
