# Generated by Django 5.2.14 on 2026-05-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. True = logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the row was soft-deleted.', null=True)),
                ('name', models.CharField(help_text="Display name of the branch (e.g. 'Vasavi Guest House').", max_length=200)),
                ('city', models.CharField(db_index=True, help_text='City where the branch is located.', max_length=100)),
                ('address', models.TextField(help_text='Full postal address of the branch.')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number for the branch.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive branches are hidden from public listings.')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ['city', 'name'],
            },
        ),
    ]
