# Generated by Django 5.2.14 on 2026-05-23 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('name', models.CharField(help_text='Room category label, e.g. Standard, Deluxe, Suite.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the room type.')),
            ],
            options={
                'verbose_name': 'room type',
                'verbose_name_plural': 'room types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. True = logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the row was soft-deleted.', null=True)),
                ('room_number', models.CharField(help_text='Room number or name.', max_length=50)),
                ('capacity', models.PositiveIntegerField(help_text='Max guest capacity.')),
                ('base_price_per_night', models.BigIntegerField(help_text='Amount in paise (₹1 = 100 paise).')),
                ('is_donor_exclusive', models.BooleanField(default=False, help_text='If True, only donors can book this room.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive rooms are hidden from availability searches.')),
                ('branch', models.ForeignKey(help_text='The branch this room belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='branches.branch')),
                ('room_type', models.ForeignKey(help_text='Category of this room.', on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'ordering': ['branch', 'room_number'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'room_number'), name='uq_branch_room_number'), models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='room_capacity_positive'), models.CheckConstraint(condition=models.Q(('base_price_per_night__gte', 0)), name='room_price_non_negative')],
            },
        ),
    ]
