# Generated by Django 5.2.14 on 2026-05-24 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_room_operational_status_and_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).'),
        ),
    ]
