# Generated by Django 5.2.14 on 2026-06-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_functionhall_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionhallimage',
            name='image',
            field=models.ImageField(help_text='Hall photo (JPEG, PNG, or WebP).', upload_to='properties.media_paths.function_hall_image_upload_to'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(help_text='Room photo (JPEG, PNG, or WebP).', upload_to='properties.media_paths.room_image_upload_to'),
        ),
    ]
