# Generated by Django 5.2.15 on 2026-06-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_convert_to_uuid_pk'),
        ('properties', '0009_fix_legacy_image_paths'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['branch', 'is_deleted', 'is_active'], name='idx_room_branch_availability'),
        ),
    ]
