import os
import random
from datetime import timedelta
from django.utils import timezone
from bookings.models import Booking
from properties.models import Room
from branches.models import Branch
from accounts.models import User
from django.db import transaction

def seed_bookings():
    users = list(User.objects.all()[:10])
    if not users:
        print("No users found! Please create some users first.")
        return

    rooms = list(Room.objects.select_related('branch', 'room_type').all())
    if not rooms:
        print("No rooms found!")
        return

    statuses = ['pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled']
    payment_statuses = ['unpaid', 'paid', 'refund_pending', 'refunded']
    gateways = ['cash', 'razorpay']

    print(f"Creating 50 random bookings...")
    
    new_bookings = []
    now = timezone.now().date()

    for i in range(50):
        room = random.choice(rooms)
        user = random.choice(users)
        
        # Random dates between last 30 days and next 30 days
        days_offset = random.randint(-30, 30)
        check_in = now + timedelta(days=days_offset)
        nights = random.randint(1, 5)
        check_out = check_in + timedelta(days=nights)
        
        status = random.choice(statuses)
        payment_status = random.choice(payment_statuses)
        
        base_amount = room.base_price_per_night * nights
        discount_amount = 0
        
        if random.random() > 0.8:
            discount_amount = base_amount // 10 # 10% discount
            
        final_amount = base_amount - discount_amount
        
        booking = Booking(
            user=user,
            room=room,
            branch=room.branch,
            check_in_date=check_in,
            check_out_date=check_out,
            nights=nights,
            guest_count=random.randint(1, room.capacity or 2),
            status=status,
            payment_status=payment_status,
            payment_gateway=random.choice(gateways),
            base_amount=base_amount,
            discount_amount=discount_amount,
            final_amount=final_amount,
            guest_name=f"Mock Guest {i}",
            guest_phone=user.phone or "9999999999",
            notes="Generated by seed script."
        )
        new_bookings.append(booking)

    with transaction.atomic():
        for b in new_bookings:
            b.save() # We use save() instead of bulk_create to trigger signals/save overrides (like booking_reference)

    print(f"Successfully created {len(new_bookings)} bookings.")

seed_bookings()
