# Generated by Django 5.2.14 on 2026-05-23 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('from_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], help_text='Status before the transition.', max_length=20)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], help_text='Status after the transition.', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason or note for the status change.')),
            ],
            options={
                'verbose_name': 'booking status log',
                'verbose_name_plural': 'booking status logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. True = logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the row was soft-deleted.', null=True)),
                ('booking_reference', models.CharField(db_index=True, editable=False, help_text='Auto-generated reference, e.g. VCI-2026-A3X7Q.', max_length=20, unique=True)),
                ('check_in_date', models.DateField(db_index=True)),
                ('check_out_date', models.DateField(db_index=True)),
                ('nights', models.PositiveIntegerField(help_text='Computed: (check_out_date - check_in_date).days.')),
                ('guest_count', models.PositiveIntegerField(default=1, help_text='Number of guests for this booking.')),
                ('guest_name', models.CharField(blank=True, help_text='Name of the guest (if different from the booking user).', max_length=200)),
                ('guest_phone', models.CharField(blank=True, help_text='Phone number of the guest.', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20)),
                ('base_amount', models.BigIntegerField(default=0, help_text='Amount in paise (₹1 = 100 paise) before coupon.')),
                ('discount_amount', models.BigIntegerField(default=0, help_text='Discount from coupon, in paise.')),
                ('final_amount', models.BigIntegerField(default=0, help_text='Charged amount in paise. Must equal base_amount - discount_amount.')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='unpaid', max_length=30)),
                ('payment_reference', models.CharField(blank=True, help_text='Razorpay or other gateway order/payment ID.', max_length=200)),
                ('payment_gateway', models.CharField(blank=True, choices=[('razorpay', 'Razorpay'), ('other', 'Other')], max_length=20)),
                ('payment_paid_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was confirmed.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this booking.')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('branch', models.ForeignKey(help_text='Denormalised from room.branch for query performance.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='branches.branch')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
