# Generated by Django 5.2.14 on 2026-05-23 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('coupons', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupons_applied',
            field=models.ManyToManyField(blank=True, help_text='Coupons redeemed against this booking.', related_name='bookings_applied', to='coupons.coupon'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(help_text='The room being booked.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='properties.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(help_text='The user who made this booking.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingstatuslog',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingstatuslog',
            name='changed_by',
            field=models.ForeignKey(help_text='The user who triggered this status change.', on_delete=django.db.models.deletion.PROTECT, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='idx_booking_user_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['branch', 'status'], name='idx_booking_branch_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in_date', 'check_out_date'], name='idx_booking_dates'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('nights__gt', 0)), name='booking_nights_positive'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('base_amount__gte', 0)), name='booking_base_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='booking_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('final_amount__gte', 0)), name='booking_final_amount_non_negative'),
        ),
    ]
