# Generated by Django 5.2.14 on 2026-05-24 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_convert_to_uuid_pk'),
        ('branches', '0002_convert_to_uuid_pk'),
        ('coupons', '0002_convert_to_uuid_pk'),
        ('properties', '0004_alter_roomimage_created_at_alter_roomimage_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_initiated_by_role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('donor', 'Donor'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('system', 'System (auto-expired)')], help_text='Role of the actor who cancelled (user/admin/super_admin/system).', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='The user who triggered the cancellation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Auto-cancel PENDING+UNPAID booking if still unresolved after this time.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay order ID (separate from payment ID).', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.BigIntegerField(default=0, help_text='Amount refunded in paise. 0 = no refund yet.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the refund was processed.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_reason',
            field=models.TextField(blank=True, help_text='Reason provided when processing the refund.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_reference',
            field=models.CharField(blank=True, help_text='Cash receipt/reference for the refund.', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the guest submitted the refund request.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_requested_reason',
            field=models.TextField(blank=True, help_text="Guest's stated reason for requesting a refund."),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('razorpay', 'Razorpay'), ('cash', 'Cash'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Cash receipt number or other payment reference.', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='unpaid', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='confirmed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'expires_at'], name='idx_booking_status_expires'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status'], name='idx_booking_payment_status'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gte', 0)), name='booking_refund_amount_non_negative'),
        ),
    ]
