# Generated by Django 5.2.14 on 2026-06-01 04:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_cancel_initiated_by_role_and_more'),
        ('branches', '0002_convert_to_uuid_pk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingExport',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('filters_applied', models.JSONField(default=dict, help_text='Snapshot of all filters + requesting user role at export time. Serves as the audit log — never mutated after creation.')),
                ('file_path', models.CharField(blank=True, help_text='Absolute path on disk.', max_length=500)),
                ('download_url', models.CharField(blank=True, help_text='Relative MEDIA_URL path.', max_length=500)),
                ('record_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='File is deleted and status set to FAILED after this timestamp.', null=True)),
                ('export_started_at', models.DateTimeField(blank=True, null=True)),
                ('export_finished_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch scope at export time. NULL = all branches (super_admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('requested_by', models.ForeignKey(help_text='Staff user who triggered this export.', on_delete=django.db.models.deletion.CASCADE, related_name='booking_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'booking export',
                'verbose_name_plural': 'booking exports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', 'status'], name='idx_bkgexport_user_status'), models.Index(fields=['status', 'expires_at'], name='idx_bkgexport_status_expires')],
            },
        ),
    ]
