# Generated by Django 5.2.14 on 2026-06-01 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_extend_booking_for_halls'),
        ('branches', '0002_convert_to_uuid_pk'),
        ('coupons', '0002_convert_to_uuid_pk'),
        ('properties', '0006_alter_functionhall_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='chk_booking_exactly_one_resource',
        ),
        migrations.AlterField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(help_text='Denormalised from room or function_hall for query performance.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='branches.branch'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('function_hall__isnull', True), ('room__isnull', False)), models.Q(('function_hall__isnull', False), ('room__isnull', True)), _connector='OR'), name='chk_booking_exactly_one_resource'),
        ),
    ]
