# Generated by Django 5.2.15 on 2026-06-14 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_booking_chk_booking_exactly_one_resource_and_more'),
        ('branches', '0002_convert_to_uuid_pk'),
        ('coupons', '0002_convert_to_uuid_pk'),
        ('properties', '0009_fix_legacy_image_paths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'check_in_date', 'check_out_date'], name='idx_booking_room_dates'),
        ),
    ]
