# Generated by Django 5.2.14 on 2026-07-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_add_composite_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingexport",
            name="estimated_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Row estimate captured when the export was requested.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookingexport",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Generation progress (0–100) for live UI updates.",
            ),
        ),
    ]
