# Generated by Django 5.2.14 on 2026-07-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_bookingexport_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingexport',
            name='download_url',
            field=models.CharField(blank=True, help_text='Staff API download path when READY (not a public media URL).', max_length=500),
        ),
        migrations.AlterField(
            model_name='bookingexport',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Generation progress (0–100) for live UI updates.'),
        ),
    ]
