# Generated by Django 5.2.14 on 2026-06-01 04:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp (set once, never updated).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Row last-modification timestamp (auto-updated on save).')),
                ('category', models.CharField(choices=[('coupon', 'Coupon'), ('donation', 'Donation'), ('user', 'User'), ('system', 'System')], max_length=20)),
                ('type', models.CharField(choices=[('coupon_redeemed', 'Coupon redeemed'), ('coupon_expired', 'Coupon expired'), ('coupon_nearing_expiry', 'Coupon nearing expiry'), ('donation_received', 'Donation received'), ('donation_approved', 'Donation approved'), ('donation_rejected', 'Donation rejected'), ('profile_updated', 'Profile updated'), ('password_changed', 'Password changed'), ('account_approved', 'Account approved'), ('system_alert', 'System alert')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('related_entity_type', models.CharField(blank=True, max_length=50)),
                ('related_entity_id', models.UUIDField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='idx_notif_recipient_read'), models.Index(fields=['recipient', 'category'], name='idx_notif_recipient_category')],
            },
        ),
    ]
